language: java
jdk:
  - openjdk8
before_script:
  - bundle exec rails runner "Webdrivers::Chromedriver.update"
addons:
  chrome: stable
script: ./mvnw clean install
      sudo apt-get install chromium-driver